name: CI
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install wasm pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Install protoc
      run: sudo apt install -y protobuf-compiler
    
    - name: Install buf command
      run: npm install -g @bufbuild/buf

    - name: Build
      run: |
        make install
        make node
        make web

    - name: Unit tests
      run: cargo test --verbose

    - name: Run test COBOL programs
      run: |
        make test
    
    - name: Build grpc-client
      run: |
        cd grpc/web-client
        yarn install
        yarn gen:services
    
    - name: Build packages for web browsers
      run: |
        cd test/www/
        npm install
        mv ../../fukutsu-cobol/ node_modules
        fcbl ../hello.cbl index.js --target=web
